import 'package:youtube_explode_dart/youtube_explode_dart.dart';
import 'dart:convert';

Future<void> main() async {
  var yt = YoutubeExplode();

  var manifest = await yt.videos.closedCaptions
      .getManifest('ppJy5uGZLi4', autoGenerated: true);
  var trackInfo = manifest.getByLanguage('en');
  var track = await yt.videos.closedCaptions.get(trackInfo.first);
  print(json.encode(track.toJson()));
}
