import 'package:youtube_explode_dart/youtube_explode_dart.dart';

Future<void> main() async {
  var yt = YoutubeExplode();

  var manifest = await yt.videos.closedCaptions
      .getManifest('Pxgvgh9IFqA', autoGenerated: true);
  print(manifest.tracks);
  print('\n\n---------------------\n\n');

  manifest = await yt.videos.closedCaptions
      .getManifest('Pxgvgh9IFqA', autoGenerated: false);
  print(manifest.tracks);
  yt.close();
}
