include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    prefer_final_locals: false
    parameter_assignments: false
    no_runtimetype_tostring: false
    avoid_escaping_inner_quotes: false
    prefer_const_constructors: true
    avoid_positional_boolean_parameters: false
