include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    prefer_final_locals: false
    parameter_assignments: false
    no_runtimetype_tostring: false
    avoid_escaping_inner_quotes: false
    prefer_const_constructors: true
    avoid_positional_boolean_parameters: false
    require_trailing_commas: false
    prefer_relative_imports: true
    avoid_relative_lib_imports: false
    always_use_package_imports: false
