// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target

part of 'closed_caption_track_info.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;

final _privateConstructorUsedError = UnsupportedError(
    'It seems like you constructed your class using `MyClass._()`. This constructor is only meant to be used by freezed and you are not supposed to need it nor use it.\nPlease check the documentation here for more informations: https://github.com/rrousselGit/freezed#custom-getters-and-methods');

ClosedCaptionTrackInfo _$ClosedCaptionTrackInfoFromJson(
    Map<String, dynamic> json) {
  return _ClosedCaptionTrackInfo.fromJson(json);
}

/// @nodoc
class _$ClosedCaptionTrackInfoTearOff {
  const _$ClosedCaptionTrackInfoTearOff();

  _ClosedCaptionTrackInfo call(Uri url, Language language,
      {bool isAutoGenerated = false, required ClosedCaptionFormat format}) {
    return _ClosedCaptionTrackInfo(
      url,
      language,
      isAutoGenerated: isAutoGenerated,
      format: format,
    );
  }

  ClosedCaptionTrackInfo fromJson(Map<String, Object?> json) {
    return ClosedCaptionTrackInfo.fromJson(json);
  }
}

/// @nodoc
const $ClosedCaptionTrackInfo = _$ClosedCaptionTrackInfoTearOff();

/// @nodoc
mixin _$ClosedCaptionTrackInfo {
  /// Manifest URL of the associated track.
  Uri get url => throw _privateConstructorUsedError;

  /// Language of the associated track.
  Language get language => throw _privateConstructorUsedError;

  /// Whether the associated track was automatically generated.
  bool get isAutoGenerated => throw _privateConstructorUsedError;

  /// Track format
  ClosedCaptionFormat get format => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $ClosedCaptionTrackInfoCopyWith<ClosedCaptionTrackInfo> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $ClosedCaptionTrackInfoCopyWith<$Res> {
  factory $ClosedCaptionTrackInfoCopyWith(ClosedCaptionTrackInfo value,
          $Res Function(ClosedCaptionTrackInfo) then) =
      _$ClosedCaptionTrackInfoCopyWithImpl<$Res>;
  $Res call(
      {Uri url,
      Language language,
      bool isAutoGenerated,
      ClosedCaptionFormat format});

  $LanguageCopyWith<$Res> get language;
}

/// @nodoc
class _$ClosedCaptionTrackInfoCopyWithImpl<$Res>
    implements $ClosedCaptionTrackInfoCopyWith<$Res> {
  _$ClosedCaptionTrackInfoCopyWithImpl(this._value, this._then);

  final ClosedCaptionTrackInfo _value;
  // ignore: unused_field
  final $Res Function(ClosedCaptionTrackInfo) _then;

  @override
  $Res call({
    Object? url = freezed,
    Object? language = freezed,
    Object? isAutoGenerated = freezed,
    Object? format = freezed,
  }) {
    return _then(_value.copyWith(
      url: url == freezed
          ? _value.url
          : url // ignore: cast_nullable_to_non_nullable
              as Uri,
      language: language == freezed
          ? _value.language
          : language // ignore: cast_nullable_to_non_nullable
              as Language,
      isAutoGenerated: isAutoGenerated == freezed
          ? _value.isAutoGenerated
          : isAutoGenerated // ignore: cast_nullable_to_non_nullable
              as bool,
      format: format == freezed
          ? _value.format
          : format // ignore: cast_nullable_to_non_nullable
              as ClosedCaptionFormat,
    ));
  }

  @override
  $LanguageCopyWith<$Res> get language {
    return $LanguageCopyWith<$Res>(_value.language, (value) {
      return _then(_value.copyWith(language: value));
    });
  }
}

/// @nodoc
abstract class _$ClosedCaptionTrackInfoCopyWith<$Res>
    implements $ClosedCaptionTrackInfoCopyWith<$Res> {
  factory _$ClosedCaptionTrackInfoCopyWith(_ClosedCaptionTrackInfo value,
          $Res Function(_ClosedCaptionTrackInfo) then) =
      __$ClosedCaptionTrackInfoCopyWithImpl<$Res>;
  @override
  $Res call(
      {Uri url,
      Language language,
      bool isAutoGenerated,
      ClosedCaptionFormat format});

  @override
  $LanguageCopyWith<$Res> get language;
}

/// @nodoc
class __$ClosedCaptionTrackInfoCopyWithImpl<$Res>
    extends _$ClosedCaptionTrackInfoCopyWithImpl<$Res>
    implements _$ClosedCaptionTrackInfoCopyWith<$Res> {
  __$ClosedCaptionTrackInfoCopyWithImpl(_ClosedCaptionTrackInfo _value,
      $Res Function(_ClosedCaptionTrackInfo) _then)
      : super(_value, (v) => _then(v as _ClosedCaptionTrackInfo));

  @override
  _ClosedCaptionTrackInfo get _value => super._value as _ClosedCaptionTrackInfo;

  @override
  $Res call({
    Object? url = freezed,
    Object? language = freezed,
    Object? isAutoGenerated = freezed,
    Object? format = freezed,
  }) {
    return _then(_ClosedCaptionTrackInfo(
      url == freezed
          ? _value.url
          : url // ignore: cast_nullable_to_non_nullable
              as Uri,
      language == freezed
          ? _value.language
          : language // ignore: cast_nullable_to_non_nullable
              as Language,
      isAutoGenerated: isAutoGenerated == freezed
          ? _value.isAutoGenerated
          : isAutoGenerated // ignore: cast_nullable_to_non_nullable
              as bool,
      format: format == freezed
          ? _value.format
          : format // ignore: cast_nullable_to_non_nullable
              as ClosedCaptionFormat,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$_ClosedCaptionTrackInfo extends _ClosedCaptionTrackInfo {
  const _$_ClosedCaptionTrackInfo(this.url, this.language,
      {this.isAutoGenerated = false, required this.format})
      : super._();

  factory _$_ClosedCaptionTrackInfo.fromJson(Map<String, dynamic> json) =>
      _$$_ClosedCaptionTrackInfoFromJson(json);

  @override

  /// Manifest URL of the associated track.
  final Uri url;
  @override

  /// Language of the associated track.
  final Language language;
  @JsonKey()
  @override

  /// Whether the associated track was automatically generated.
  final bool isAutoGenerated;
  @override

  /// Track format
  final ClosedCaptionFormat format;

  @override
  bool operator ==(dynamic other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _ClosedCaptionTrackInfo &&
            const DeepCollectionEquality().equals(other.url, url) &&
            const DeepCollectionEquality().equals(other.language, language) &&
            const DeepCollectionEquality()
                .equals(other.isAutoGenerated, isAutoGenerated) &&
            const DeepCollectionEquality().equals(other.format, format));
  }

  @override
  int get hashCode => Object.hash(
      runtimeType,
      const DeepCollectionEquality().hash(url),
      const DeepCollectionEquality().hash(language),
      const DeepCollectionEquality().hash(isAutoGenerated),
      const DeepCollectionEquality().hash(format));

  @JsonKey(ignore: true)
  @override
  _$ClosedCaptionTrackInfoCopyWith<_ClosedCaptionTrackInfo> get copyWith =>
      __$ClosedCaptionTrackInfoCopyWithImpl<_ClosedCaptionTrackInfo>(
          this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$_ClosedCaptionTrackInfoToJson(this);
  }
}

abstract class _ClosedCaptionTrackInfo extends ClosedCaptionTrackInfo {
  const factory _ClosedCaptionTrackInfo(Uri url, Language language,
      {bool isAutoGenerated,
      required ClosedCaptionFormat format}) = _$_ClosedCaptionTrackInfo;
  const _ClosedCaptionTrackInfo._() : super._();

  factory _ClosedCaptionTrackInfo.fromJson(Map<String, dynamic> json) =
      _$_ClosedCaptionTrackInfo.fromJson;

  @override

  /// Manifest URL of the associated track.
  Uri get url;
  @override

  /// Language of the associated track.
  Language get language;
  @override

  /// Whether the associated track was automatically generated.
  bool get isAutoGenerated;
  @override

  /// Track format
  ClosedCaptionFormat get format;
  @override
  @JsonKey(ignore: true)
  _$ClosedCaptionTrackInfoCopyWith<_ClosedCaptionTrackInfo> get copyWith =>
      throw _privateConstructorUsedError;
}
