// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'closed_caption_track_info.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_ClosedCaptionTrackInfo _$$_ClosedCaptionTrackInfoFromJson(
        Map<String, dynamic> json) =>
    _$_ClosedCaptionTrackInfo(
      Uri.parse(json['url'] as String),
      Language.fromJson(json['language'] as Map<String, dynamic>),
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
      format:
          ClosedCaptionFormat.fromJson(json['format'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$$_ClosedCaptionTrackInfoToJson(
        _$_ClosedCaptionTrackInfo instance) =>
    <String, dynamic>{
      'url': instance.url.toString(),
      'language': instance.language,
      'isAutoGenerated': instance.isAutoGenerated,
      'format': instance.format,
    };
